<template xmlns:v-slot="http://www.w3.org/1999/XSL/Transform">
<v-container>
<!-- main home page start -->
  <v-layout align-center justify-center row>
    <v-flex>
        <v-dialog v-model="dialog" fullscreen hide-overlay transition="dialog-bottom-transition">
          <template v-slot:activator="{ on }">
            <v-container text-xs-center class="home-btn">
              <v-layout justify-center row fill-height wrap>
                <v-flex xs12>
                  <v-btn
                    flat
                    round
                    class="text-capitalize btn-grad white--text yellow amber lighten-1 font-weight-black title "
                    v-on="on"
                  >Wow, You  found it !
                    <v-icon class="upload-icon ml-4" regular right>fal fa-cloud-upload</v-icon>
                  </v-btn>
                </v-flex>
                <v-flex xs12>
                  <v-img :src="imageBanner"></v-img>
                </v-flex>
              </v-layout>
            </v-container>
          </template>
<!--         main home page end -->
<!--       start user form (second toolbar start)  -->
          <v-card>
            <v-toolbar dark flat class="amber lighten-1">
              <v-btn icon dark @click="dialog = false">
                <v-icon>far fa-times-circle</v-icon>
              </v-btn>
              <v-toolbar-title>3 steps that you can help others to find their stuff</v-toolbar-title>
              <v-spacer></v-spacer>
              <v-toolbar-items>
                <v-btn type="submit" form ="warehouseItemUpload" dark flat :disabled="!formIsValid"  class="text-capitalize subheading upload-text" >Submit</v-btn>
              </v-toolbar-items>
            </v-toolbar>
<!--         second toolbar end   -->
            <v-container text-xs-left class="ml-0">
              <form ref="form" @submit.prevent="onCreateWarehouseItem" id="warehouseItemUpload">
                <v-layout row justify-start wrap>
                 <v-flex xs12 class="form-text-font">
                  <p class="subheading form-text-heading">
                    <v-icon class="mr-1" color="#40C4FF">fal fa-layer-group</v-icon>
                    What types of stuff you found ?
                  </p>
                   <v-combobox
                     name="category"
                     id="category"
                     flat
                     clearable
                     clear-icon="fal fa-times-circle"
                     color="success"
                     v-model="category"
                     :items="itemsCategory"
                     label="Is that a wallet or anything else"
                     :rules="[rules.required]"
                     placeholder="Wallet?"
                   >
                   </v-combobox>
                 </v-flex>
                 <v-flex xs12 class="form-text-font">
                   <p class="subheading form-text-heading" style="display: inline">
                     <v-icon class="mr-1" color="#40C4FF">fal fa-image</v-icon>
                     What does stuff look like ?
                   </p>
                   <v-tooltip top color="#FBC02D">
                     <template v-slot:activator="{ on }">
                       <v-btn
                         v-on="on"
                         small
                         raised
                         round
                         flat
                         class="amber lighten-2 text-capitalize white--text ml-4"
                         @click="onPickFile"
                         style="cursor: pointer"
                       >Add/Replace Image</v-btn>
                     </template>
                     <span class="tooltip-text">The image size has to be less than 1MB</span>
                   </v-tooltip>
                   <input
                     type="file"
                     style="display: none"
                     ref="fileInput"
                     accept="image/*"
                     @change="onFilePicked"
                   >
                 </v-flex>
                  <v-flex>
                    <v-card max-width="450" class="text-xs-center">
                        <img
                          style="vertical-align: middle"
                          :src ="imageUrl"
                          height="250"
                          id="imageUrl"
                          alt="">
                    </v-card>
                  </v-flex>
                </v-layout>
<!--                set a divider-->
                <v-divider class="my-4"></v-divider>
<!--                set found location-->
                <v-layout row justify-start wrap>
                  <v-flex xs12 class="form-text-font">
                   <p class="subheading form-text-heading">
                     <v-icon class="mr-1" color="#40C4FF">fal fa-location</v-icon>
                     Please tell us the approximate location or places , that helps owners to remind where they lost their stuffs</p>
                    <v-combobox
                      id="foundAt"
                      name="foundAt"
                      v-model="foundAt"
                      :items="dunedinDistrict"
                      :key="dunedinDistrict.key"
                      :search-input.sync="search"
                      hint="maximum of 1 regions or places"
                      persistent-hint
                      label= "You found it at/in..."
                      color="#B388FF"
                      :rules="[rules.required]"
                      prepend-inner-icon="fal fa-map-marker-check"
                      clear-icon="fal fa-times-circle"
                      clearable
                      >
                      <template v-slot:no-data>
                        <v-list-tile>
                          <v-list-tile-content>
                            <v-list-tile-title>
                              No places matching "<strong>{{ search }}</strong>".Press
                              <kbd>enter</kbd> to create an one.
                            </v-list-tile-title>
                          </v-list-tile-content>
                        </v-list-tile>
                      </template>
                      <template v-slot:selection="data">
                        <v-chip
                          small
                          :key="JSON.stringify(data.item)"
                          :selected="data.selected"
                          :disabled="data.disabled"
                          class="v-chip--select-multi"
                          @input="data.parent.selectItem(data.item)"
                        >
                          <v-avatar
                            class="deep-purple lighten-3 white--text"
                            v-text="data.item.slice(0, 1).toUpperCase()"
                          ></v-avatar>
                          {{ data.item }}
                        </v-chip>
                      </template>
                    </v-combobox>
<!--                    set a divider-->
                    <v-divider class="my-5"></v-divider>
                    <p class="subheading form-text-heading">
                      <v-icon class="mr-1" color="#40C4FF">fal fa-clipboard</v-icon>
                      Please leave a note, which ways they can get their stuff back...
                    </p>
                    <v-textarea
                      name="note"
                      id="note"
                      v-model="note"
                      :counter="100"
                      :rules="noteRules"
                      required
                      color="#FFC107"
                      outline
                      flat
                      placeholder="Note might be your Phone Number/Email or pure note, Also you can bring the stuff to your nearest City Mini Market, We will put it into our LostFounds warehouse...  "
                    >
                    </v-textarea>
                  </v-flex>
                </v-layout>
              </form>
            </v-container>
          </v-card>
        </v-dialog>
    </v-flex>
  </v-layout>
</v-container>
</template>

<script>
import db from '../firebase/firebaseinit'
import firebase from 'firebase'
export default {
  name: 'Home',
  data () {
    return {
      imageUrl: '',
      note: '',
      category: '',
      foundAt: '',
      // set item category combobox
      itemsCategory: [
        'Book',
        'Cellphone',
        'Drive License',
        'Iphone',
        'Id card',
        'Laptop',
        'Purse',
        'Student Id card',
        'Wallet'
      ],
      dunedinDistrict: [
        'Abbotsford, Runciman St',
        'Abbotsford, Torquay St',
        'Abbotsford, Abbotts Hill Rd',
        'Abbotsford, Alexander St',
        'Abbotsford, Binnie St',
        'Abbotsford, Christie St',
        'Abbotsford, Dall St',
        'Abbotsford, Edward St',
        'Abbotsford, Exeter St',
        'Abbotsford, Exmouth St',
        'Abbotsford, Freeman CI',
        'Abbotsford, Hyslop St',
        'Abbotsford, John St',
        'Abbotsford, Lambert St',
        'Abbotsford, Lethaby St',
        'Abbotsford, Matthew St',
        'Abbotsford, McKinlay Rd',
        'Abbotsford, McMeakin Rd',
        'Abbotsford, Mitchell St',
        'Abbotsford, North Taieri Rd',
        'Abbotsford, Paterson St',
        'Abbotsford, Penrich St',
        'Abbotsford, Shipka St',
        'Abbotsford, Shulma St',
        'Abbotsford, Teignmouth St',
        'Abbotsford, Totness St',
        'Adams Building',
        'Andersons Bay, Bayfield Rd',
        'Andersons Bay, Cranston St',
        'Andersons Bay, Darnell St',
        'Andersons Bay, Duckworth St',
        'Andersons Bay, Elliot St',
        'Andersons Bay, Everton Rd',
        'Andersons Bay, Every St',
        'Andersons Bay, Glenfinnan PI',
        'Andersons Bay, Gloucester St',
        'Andersons Bay, Heath St',
        'Andersons Bay, Hunt St',
        'Andersons Bay, Jeffery St',
        'Andersons Bay, Kinvig St',
        'Andersons Bay, Lauriston St',
        'Andersons Bay, Leyden Tce',
        'Andersons Bay, Merchiston St',
        'Andersons Bay, Meuse Lane',
        'Andersons Bay, Minto St',
        'Andersons Bay, Oakland St',
        'Andersons Bay, Puketai St',
        'Andersons Bay, Silverton St',
        'Andersons Bay, Somerville St',
        'Andersons Bay, Spencer St',
        'Andersons Bay, Stirling St',
        'Andersons Bay, Sunbury St',
        'Andersons Bay, Tahuna Rd',
        'Andersons Bay, Tomahawk Rd',
        'Andersons Bay, WoodSide Tce',
        'Archway Building(international)',
        'Archway Lecture Theatres(Otago)',
        'Arts Building(Otago)',
        'Balaclava, Blackford St',
        'Balaclava, Buckingham St',
        'Balaclava, Dorset St',
        'Balaclava, Forbes St',
        'Balaclava, Lancefield St',
        'Balaclava, Nolan St',
        'Balaclava, Pennefather St',
        'Balaclava, Raglan St',
        'Balaclava, Renfrew St',
        'Balaclava, Warwick St',
        'Balaclava, Wills St',
        'Belleknowes, Harcourt St',
        'Belleknowes, Pitcairn St',
        'Belleknowes, Alison Cres',
        'Belleknowes, Ashley St',
        'Belleknowes, Beaumont Rd',
        'Belleknowes, Belleknowes Tce',
        'Belleknowes, Bellevue St',
        'Belleknowes, Beta St',
        'Belleknowes, Bright St',
        'Belleknowes, Carnarvon St',
        'Belleknowes, Delta St',
        'Belleknowes, Epsilon St',
        'Belleknowes, Gamma St',
        'Belleknowes, Granville Tce',
        'Belleknowes, Hart St',
        'Belleknowes, Highgate',
        'Belleknowes, Jubilee St',
        'Belleknowes, Lonsdale St',
        'Belleknowes, Lonsdale Tce',
        'Belleknowes, Michie St',
        'Belleknowes, Napier St',
        'Belleknowes, Northview Cres',
        'Belleknowes, Preston Cres',
        'Belleknowes, Rosebery St',
        'Benham Building',
        'Biochemistry Building(Otago)',
        'Black/Sale House(Music)',
        'Botany Building(Otago)',
        'Botany Compressor Building(Otago)',
        'Botany Garage(Otago)',
        'Botany Old Pavillion(Otago)',
        'Botany Research Building(Otago)',
        'Botany School Annexe(Otago)',
        'Bradford, Hector St',
        'Bradford, Manchester St',
        'Bradford, Mulberry Lane',
        'Bradford, St Albans CI',
        'Bradford, Bradford St',
        'Bradford, Glenelg St',
        'Bradford, Ipswich St',
        'Bradford, Kaikorai Valley Rd',
        'Bradford, Lixmont St',
        'Bradford, Marshall St',
        'Bradford, Ronay St',
        'Bradford, Salisbury Rd',
        'Bradford, St Albans St',
        'Brighton, Copeland St',
        'Brighton, Mclntosh Rd',
        'Brighton, Pearse St',
        'Brighton, Bath St',
        'Brighton, Bedford Pde',
        'Brighton, Cole St',
        'Brighton, Hastings St',
        'Brighton, Mclntosh Rd',
        'Brighton, Morse St',
        'Brighton, Queen St',
        'Brighton, Scroggs Hill Rd',
        'Brighton, Seaview Rd',
        'Brighton, Taylor St',
        'Brighton, Trecastell St',
        'Brighton, Wells St',
        'Broad Bay, Holm Ave',
        'Broad Bay, Oxley Cres',
        'Broad Bay, Bacon St',
        'Broad Bay, Camp St',
        'Broad Bay, Clearwater St',
        'Broad Bay, Cowal St',
        'Broad Bay, Frances St',
        'Broad Bay, Greig St',
        'Broad Bay, Gwyn St',
        'Broad Bay, King George St',
        'Broad Bay, Margate Ave',
        'Broad Bay, Matariki St',
        'Broad Bay, Moerangi St',
        'Broad Bay, Portobello Rd',
        'Broad Bay, Roebuck Rise',
        'Broad Bay, Sandpiper St',
        'Broad Bay, Solar Tce',
        'Broad Bay, Virginia Ave',
        'Broad Bay, Waikana St',
        'Brockville, Barton St',
        'Brockville, Brockville Rd',
        'Brockville, Caldwell St',
        'Brockville, Cockerell St',
        'Brockville, Dalziel Rd',
        'Brockville, Domigan St',
        'Brockville, Grigor St',
        'Brockville, Herron St',
        'Brockville, McCurdy St',
        'Brockville, McDonald St',
        'Brockville, Nutsford St',
        'Brockville, Sanda Rd',
        'Brockville, Saunders St',
        'Brockville, Sretlaw PI',
        'Brockville, Statham St',
        'Brockville, Thrnbull St',
        'Brockville, Tracey St',
        'Brockville, Travis St',
        'Brockville, Wray St',
        'Burnside, Eclipse Rd',
        'Burnside, Ensor St',
        'Burnside, Kaikorai Valley Rd',
        'Burnside, McLeods Rd',
        'Burnside, Short St',
        'Calton Hill, Burnett St',
        'Calton Hill, Caversham Valley Rd',
        'Calton Hill, Columba Ave',
        'Calton Hill, Cuba St',
        'Calton Hill, Mariner St',
        'Calton Hill, Milford Ave',
        'Calton Hill, Nottingham Cres',
        'Calton Hill, Panmure Ave',
        'Calton Hill, Pladda St',
        'Calton Hill, Riselaw Rd',
        'Calton Hill, Ryehill St',
        'Calton Hill, Sidey St',
        'Calton Hill, Waimea Ave',
        'Castle Theatres(Otago)',
        'Caversham, College St',
        'Caversham, Hudson St',
        'Caversham, MacBeth St',
        'Caversham, Murray St',
        'Caversham, Alfred St',
        'Caversham, Asquith St',
        'Caversham, Baker St',
        'Caversham, Balance St',
        'Caversham, Barnes Dr',
        'Caversham, Catherine St',
        'Caversham, Caversham PI',
        'Caversham, Cole St',
        'Caversham, David St',
        'Caversham, Eastbourne St',
        'Caversham, Edwin St',
        'Caversham, Embo St',
        'Caversham, Fitzroy St',
        'Caversham, Goodall St',
        'Caversham, Hazel Ave',
        'Caversham, Hazelhurst Pass',
        'Caversham, Josephine St',
        'Caversham, Laing St',
        'Caversham, Law St',
        'Caversham, Lindsay Rd',
        'Caversham, Lisburn Ave',
        'Caversham, Lomond St',
        'Caversham, Morrison St',
        'Caversham, Murrayfield St',
        'Caversham, Pencarrow St',
        'Caversham, Peter St',
        'Caversham, Playfair St',
        'Caversham, Ranfurly',
        'Caversham, Ruskin Tce',
        'Caversham, Rutherford St',
        'Caversham, Shortland St',
        'Caversham, Station Rd',
        'Caversham, Sydney St',
        'Caversham, Thorn St',
        'Central Library(Otago)',
        'City Mini Market(21 Frederick St)',
        'City Mini Market(241 Moray PI)',
        'City Mini Market(90 Princes St)',
        'Clocktower(Otago)',
        'Clyde Hill, Bridge St',
        'Clyde Hill, Dacre Crt',
        'Clyde Hill, Forfar St',
        'Clyde Hill, Leckhampton',
        'Clyde Hill, St Heliers Crt',
        'Commerce Building(Otago Business School)',
        'Company Bay, Glenfinlass St',
        'Company Bay, McTaggart St',
        'Company Bay, Castlewood Rd',
        'Company Bay, Hinkley Tce',
        'Company Bay, Lauder St',
        'Company Bay, Luss Rd',
        'Company Bay, Mission Cv',
        'Company Bay, Newbury St',
        'Company Bay, Raynbird St',
        'Concord, Mary St',
        'Concord, Samson Rd',
        'Concord, Thoreau St',
        'Concord, Bell Cres',
        'Concord, Blackhead Rd',
        'Concord, Craig Hendry St',
        'Concord, Davies St',
        'Concord, Emerson St',
        'Concord, May St',
        'Concord, Morris St',
        'Concord, Morton St',
        'Concord, Mulford St',
        'Concord, Orr St',
        'Concord, Roy Cres',
        'Concord, Stevenson Rd',
        'Concord, Winifred St',
        'Consumer and Applied Sciences Building(Otago)',
        'Corstorphine, Summertime Ave',
        'Corstorphine, Traquair St',
        'Corstorphine, Avondale St',
        'Corstorphine, Bruntsfield PI',
        'Corstorphine, Clermiston Ave',
        'Corstorphine, Corstorphine Rd',
        'Corstorphine, Crammond Ave',
        'Corstorphine, Dovecote Ave',
        'Corstorphine, Gilmerton St',
        'Corstorphine, Hillhead Rd',
        'Corstorphine, Hilltop Cres',
        'Corstorphine, Middleton Rd',
        'Corstorphine, Milburn St',
        'Corstorphine, Ponton St',
        'Corstorphine, St Clair CI',
        'Corstorphine, Stenhope Cres',
        'Corstorphine, Westgate',
        'Dalmore, Chetham Ave',
        'Dalmore, Clifford St',
        'Dalmore, Dunedin-Waitati Rd',
        'Dalmore, Falkirk St',
        'Dalmore, Fea St',
        'Dalmore, Fortune St',
        'Dalmore, Gladstone Rd',
        'Dalmore, Orbell St',
        'Dalmore, Ramsay',
        'Dunedin Airport',
        'Diabetes Otago Inc old building',
        'Dietetics Clinics',
        'Dunedin Central, Cobden St',
        'Dunedin Central, Adam St',
        'Dunedin Central, Airedale St',
        'Dunedin Central, Albion PI',
        'Dunedin Central, Alva St',
        'Dunedin Central, Anzac Ave',
        'Dunedin Central, Arthur St',
        'Dunedin Central, Awatea St',
        'Dunedin Central, Bath St',
        'Dunedin Central, Bauchop St',
        'Dunedin Central, Birch St',
        'Dunedin Central, Bishops PI',
        'Dunedin Central, Bishops Rd',
        'Dunedin Central, Bombay St',
        'Dunedin Central, Bond st',
        'Dunedin Central, Bow Lane',
        'Dunedin Central, Braid Rd',
        'Dunedin Central, Broadway',
        'Dunedin Central, Brown St',
        'Dunedin Central, Buller St',
        'Dunedin Central, Cambria PI',
        'Dunedin Central, Canongate',
        'Dunedin Central, Cargill St',
        'Dunedin Central, Carroll St',
        'Dunedin Central, Castle St',
        'Dunedin Central, Clark St',
        'Dunedin Central, Constitution St',
        'Dunedin Central, Corrie St',
        'Dunedin Central, Crawford St',
        'Dunedin Central, Cresswell St',
        'Dunedin Central, Cumberland St ',
        'Dunedin Central, Devon St',
        'Dunedin Central, Dowling St',
        'Dunedin Central, Dunbar St',
        'Dunedin Central, Duncan St',
        'Dunedin Central, Elder St',
        'Dunedin Central, Elm Row',
        'Dunedin Central, Fernhill St',
        'Dunedin Central, Filleul St',
        'Dunedin Central, Fish St',
        'Dunedin Central, French St',
        'Dunedin Central, Fryatt St',
        'Dunedin Central, George St',
        'Dunedin Central, Gordon St',
        'Dunedin Central, Graham St',
        'Dunedin Central, Grange St',
        'Dunedin Central, Grant St',
        'Dunedin Central, Great Kind St ',
        'Dunedin Central, Haddon PI',
        'Dunedin Central, Halsey St',
        'Dunedin Central, Harrow St',
        'Dunedin Central, Heriot Row',
        'Dunedin Central, High St',
        'Dunedin Central, Hope St',
        'Dunedin Central, Jervois St',
        'Dunedin Central, Jetty St',
        'Dunedin Central, Jones St',
        'Dunedin Central, Jutland St',
        'Dunedin Central, Kitchener St',
        'Dunedin Central, Lees St',
        'Dunedin Central, Liverpool St',
        'Dunedin Central, London St',
        'Dunedin Central, MacLaggan St',
        'Dunedin Central, Magnet St',
        'Dunedin Central, Maitland St',
        'Dunedin Central, Manor PI',
        'Dunedin Central, Manse St',
        'Dunedin Central, Maori Rd',
        'Dunedin Central, Mason St',
        'Dunedin Central, Melville St',
        'Dunedin Central, Montpellier St',
        'Dunedin Central, Moray PI',
        'Dunedin Central, Parry St',
        'Dunedin Central, Police St',
        'Dunedin Central, Princes St',
        'Dunedin Central, Queens Dr',
        'Dunedin Central, Queens Gdns',
        'Dunedin Central, Rattray St',
        'Dunedin Central, Roberts St',
        'Dunedin Central, Royal Tce',
        'Dunedin Central, Russell St',
        'Dunedin Central, Scotland St',
        'Dunedin Central, Serpentine Ave',
        'Dunedin Central, Smith St',
        'Dunedin Central, St Andrew St',
        'Dunedin Central, Stafford St',
        'Dunedin Central, Steep St',
        'Dunedin Central, Stoutgate',
        'Dunedin Central, Stuart St',
        'Dunedin Central, Sturdee St',
        'Dunedin Central, Sutherland St',
        'Dunedin Central, Tennyson St',
        'Dunedin Central, Tewsley St',
        'Dunedin Central, The Octagon',
        'Dunedin Central, Thomas Burns St',
        'Dunedin Central, View St',
        'Dunedin Central, Vire St',
        'Dunedin Central, Vogel St',
        'Dunedin Central, Ward St',
        'Dunedin Central, Water St',
        'Dunedin Central, Wharf St',
        'Dunedin Central, White St',
        'Dunedin Central, Wickliffe St',
        'Dunedin Central, William St',
        'Dunedin Central, Willis St',
        'Dunedin Central, Wolseley St',
        'Dunedin Central, York PI',
        'Dunedin Hospital',
        'Fairfield, Alfred PI',
        'Fairfield, Bellona Lane',
        'Fairfield, Blanc Ave',
        'Fairfield, Bremner St',
        'Fairfield, Centennial Rd',
        'Fairfield, Centennial Rd',
        'Fairfield, Chadwick St',
        'Fairfield, Coach Rd',
        'Fairfield, Cockburn St',
        'Fairfield, Edith St',
        'Fairfield, Estuary Cres',
        'Fairfield, Fairplay St',
        'Fairfield, Flower St',
        'Fairfield, Freyberg Rd',
        'Fairfield, Fry St',
        'Fairfield, Hartley St',
        'Fairfield, Hogan PI',
        'Fairfield, Holyport CI',
        'Fairfield, Kennedy Rd',
        'Fairfield, Main Rd',
        'Fairfield, Martin R',
        'Fairfield, Morris Rd',
        'Fairfield, Old Brighton Rd',
        'Fairfield, Park Lane',
        'Fairfield, Robert St',
        'Fairfield, Saddleview PI',
        'Fairfield, Sickels St',
        'Fairfield, St James PI',
        'Fairfield, Sunninghurst Dr',
        'Fairfield, Walton Park Ave',
        'Forbury, Loyalty St',
        'Forbury, Helena St',
        'Forbury, Nelson St',
        'Forbury, Nicholson St',
        'Forbury, Richmond St',
        'Forbury, Surrey St',
        'Forbury, Sussex St',
        'Fraser Building',
        'Glenleith, Andail St',
        'Glenleith, Booth Rd',
        'Glenleith, Clarewood Ave',
        'Glenleith, Fulton Rd',
        'Glenleith, Garden PI',
        'Glenleith, Glenholm St',
        'Glenleith, Glenmore St',
        'Glenleith, Hadley CI',
        'Glenleith, Islay St',
        'Glenleith, Leithton CI',
        'Glenleith, McGlashan St',
        'Glenleith, Rockside RD',
        'Glenleith, Tanner Rd',
        'Glenross, Charters St',
        'Glenross, Colquhoun St',
        'Glenross, Ettrick St',
        'Glenross, Frasers Rd',
        'Glenross, Glenross St',
        'Glenross, Hermond St',
        'Green Island, Bideford St',
        'Green Island, Abbotsford Rd',
        'Green Island, Allen Rd',
        'Green Island, Benfell St',
        'Green Island, Boomer St',
        'Green Island, Brighton Rd',
        'Green Island, Brooklyn St',
        'Green Island, Burgess St',
        'Green Island, Carnforth St',
        'Green Island, Church Hill Rd',
        'Green Island, Church St',
        'Green Island, Clariton Ave',
        'Green Island, Corbett St',
        'Green Island, Crimp St',
        'Green Island, Derby St',
        'Green Island, Devonport St',
        'Green Island, District Rd',
        'Green Island, Edinburgh St',
        'Green Island, Elwyn Cres',
        'Green Island, Geddes St',
        'Green Island, Grandvista Dr',
        'Green Island, Harraway Rd',
        'Green Island, Harrison St',
        'Green Island, Howden St',
        'Green Island, Irmo St',
        'Green Island, Jenkins St',
        'Green Island, Jensen St',
        'Green Island, Kaler St',
        'Green Island, Kane St',
        'Green Island, Kirkland St',
        'Green Island, Koremata St',
        'Green Island, Loudon St',
        'Green Island, Main South Rd',
        'Green Island, Miller St',
        'Green Island, Neill St',
        'Green Island, Orange St',
        'Green Island, Owen St',
        'Green Island, Pottinger St',
        'Green Island, Price St',
        'Green Island, Prosser St',
        'Green Island, Quarry Rd',
        'Green Island, Reeves St',
        'Green Island, Rennie St',
        'Green Island, Scotland Tce',
        'Green Island, Severn St',
        'Green Island, Shand St',
        'Green Island, Shanks St',
        'Green Island, Sunnyvale Lane',
        'Green Island, Taylor St',
        'Green Island, Thomson St',
        'Green Island, Tomkins St',
        'Green Island, Unsworth St',
        'Green Island, Waldron Cres',
        'Green Island, Watson St',
        'Green Island, Weir St',
        'Green Island, Westland St',
        'Green Island, Will St',
        'Gregory Building(Otago)',
        'Halfway Bush, kohu PI',
        'Halfway Bush, Arcadia PI',
        'Halfway Bush, Ashmore St',
        'Halfway Bush, Balmain St',
        'Halfway Bush, Blake St',
        'Halfway Bush, Bonar St',
        'Halfway Bush, Colinsay St',
        'Halfway Bush, Dalziel Rd',
        'Halfway Bush, Ellersley St',
        'Halfway Bush, Fenwick St',
        'Halfway Bush, Gilkison St',
        'Halfway Bush, Hanlon St',
        'Halfway Bush, Helensburgh Rd',
        'Halfway Bush, Kereru CI',
        'Halfway Bush, Lincoln St',
        'Halfway Bush, Mooltan St',
        'Halfway Bush, Raoulia CI',
        'Halfway Bush, Rudd Rd',
        'Halfway Bush, Salmond St',
        'Halfway Bush, Spiers Rd',
        'Halfway Bush, Stephen St',
        'Halfway Bush, Strode St',
        'Halfway Bush, Taieri Rd',
        'Halfway Bush, Thesis St',
        'Halfway Bush, Three Mile Hill Rd',
        'Halfway Bush, Tilburn St',
        'Halfway Bush, Turner St',
        'Health Sciences Library(Otago)',
        'Helensburgh, Burma Rd',
        'Helensburgh, Centennial Ave',
        'Helensburgh, Derwent St',
        'Helensburgh, Honeystone St',
        'Helensburgh, Jason St',
        'Helensburgh, Joshua PI',
        'Helensburgh, Larkins St',
        'Helensburgh, Pioneer Cres',
        'Helensburgh, Polwarth Rd',
        'Helensburgh, Upland St',
        'Helensburgh, Wakari Rd',
        'Hercus Building',
        'Highcliff, Hilton Rd',
        'Hocken Library(Otago)',
        'Kaikorai, Ann St',
        'Kaikorai, Ayr St',
        'Kaikorai, Belgrave Cres',
        'Kaikorai, Beresford St',
        'Kaikorai, Chapel St',
        'Kaikorai, Coleridge St',
        'Kaikorai, County Rd',
        'Kaikorai, Culloden St',
        'Kaikorai, Dale St',
        'Kaikorai, Dean St',
        'Kaikorai, Eton St',
        'Kaikorai, Falcon St',
        'Kaikorai, Farley St',
        'Kaikorai, Fife St',
        'Kaikorai, Font St',
        'Kaikorai, Gibson St',
        'Kaikorai, Gowry PI',
        'Kaikorai, Greenock St',
        'Kaikorai, Jellicoe Cres',
        'Kaikorai, Kaikorai Valley Rd',
        'Kaikorai, Kinsman St',
        'Kaikorai, Lismore Lane',
        'Kaikorai, Loom St',
        'Kaikorai, Lundie St',
        'Kaikorai, Malta St',
        'Kaikorai, Mardale St',
        'Kaikorai, Mellor St',
        'Kaikorai, Nairn St',
        'Kaikorai, Oates St',
        'Kaikorai, Oban St',
        'Kaikorai, School St',
        'Kaikorai, Swanson St',
        'Kaikorai, Wairoa St',
        'Kaikorai, Walton St',
        'Kaikorai, Wright S',
        'Kenmure, Agnes St',
        'Kenmure, Barr St',
        'Kenmure, Bernard St',
        'Kenmure, Blair St',
        'Kenmure, Borthwick St',
        'Kenmure, Bryant St',
        'Kenmure, Donald St',
        'Kenmure, Elgin Rd',
        'Kenmure, Elizabeth St',
        'Kenmure, English Ave',
        'Kenmure, Fels St',
        'Kenmure, Hocken St',
        'Kenmure, Kenmure Rd',
        'Kenmure, Leary St',
        'Kenmure, Mataora Rd',
        'Kenmure, McNab St',
        'Kenmure, Mercer St',
        'Kenmure, Mornington Rd',
        'Kenmure, Netherby St',
        'Kenmure, Shirley PI',
        'Kenmure, Stanley St',
        'Kenmure, Stansfield St',
        'Kenmure, Stone St',
        'Kensington, Ardmore Dr',
        'Kensington, Bridgman St',
        'Kensington, Grosvenor St',
        'Kensington, Percy St',
        'Kensington, Phillips St',
        'Kensington, Wain st',
        'Kensington, Wilkie Rd',
        'Kew, Bangor Tce',
        'Kew, Dornoch St',
        'Kew, Easther Cres',
        'Kew, Lockerbie St',
        'Kew, Marewa St',
        'Kew, Rainton Rd',
        'Kew, Seaview Tce',
        'Kew, Winston PI',
        'Laboratory Annexe(Otago)',
        'Language centre(Otago)',
        'Law Library(Otago)',
        'Lawyers Head, John Wilson Ocean Dr',
        'Leith St',
        'Leith Valley, Leith Valley Rd',
        'Leith Valley, Poulters Rd',
        'Liberton, Allenby Ave',
        'Liberton, Blundell St',
        'Liberton, Dover St',
        'Liberton, Egmont St',
        'Liberton, Forrester Ave',
        'Liberton, Hillary St',
        'Liberton, Hislop St',
        'Liberton, Lowe St',
        'Liberton, Newhaven St',
        'Liberton, Pine Hill Rd',
        'Liberton, Raleigh St',
        'Liberton, Tasman St',
        'Liberton, Tensing st',
        'Liberton, Truby King Cres',
        'Liberton, Wilkinson St',
        'Lindo Ferguson Building(Otago)',
        'Lookout Point, Aberfeldy St',
        'Lookout Point, Robinson St',
        'Lookout Point, Thomson St',
        'Macandrew Bay, Greenacres St',
        'Macandrew Bay, Howard St',
        'Macandrew Bay, Barling St',
        'Macandrew Bay, Bayne Tce',
        'Macandrew Bay, Bewley Ave',
        'Macandrew Bay, Conway St',
        'Macandrew Bay, Dickson St',
        'Macandrew Bay, Featherston St',
        'Macandrew Bay, Gorman St',
        'Macandrew Bay, Hellyer St',
        'Macandrew Bay, Jane St',
        'Macandrew Bay, Kellas St',
        'Macandrew Bay, Marett St',
        'Macandrew Bay, Marine Pde',
        'Macandrew Bay, Marion St',
        'Macandrew Bay, McLelland St',
        'Macandrew Bay, Ngaio',
        'Macandrew Bay, Porterfield St',
        'Macandrew Bay, Roger',
        'Macandrew Bay, Wharfdale St',
        'Maia, Babsie Rd',
        'Maia, De Lacy St',
        'Maia, Fern Rd',
        'Maia, Jessie St',
        'Maia, Manapouri St',
        'Maia, Rotoiti St',
        'Maori Hill, Baxter St',
        'Maori Hill, Braeview Cres',
        'Maori Hill, Braeview Cres',
        'Maori Hill, Brent St',
        'Maori Hill, Brownville Cres',
        'Maori Hill, Burwood Av',
        'Maori Hill, Butler St',
        'Maori Hill, Cairnhill St',
        'Maori Hill, Cannington Rd',
        'Maori Hill, Chamberlain St',
        'Maori Hill, Claremont St',
        'Maori Hill, Como st',
        'Maori Hill, Drivers Rd',
        'Maori Hill, Dudley PI',
        'Maori Hill, Dunblane St',
        'Maori Hill, Fairfax St',
        'Maori Hill, Falkland St',
        'Maori Hill, Grater St',
        'Maori Hill, Grater St',
        'Maori Hill, Grendon St',
        'Maori Hill, Hamel St',
        'Maori Hill, Henry St',
        'Maori Hill, Lothian St',
        'Maori Hill, Lynwood Ave',
        'Maori Hill, Maheno St',
        'Maori Hill, McMillan St',
        'Maori Hill, Monro St',
        'Maori Hill, Newington Ave',
        'Maori Hill, Passmore Cres',
        'Maori Hill, Pilkington St',
        'Maori Hill, Pollock St',
        'Maori Hill, Prestwick St',
        'Maori Hill, Sargood St',
        'Maori Hill, Sim St',
        'Maori Hill, Spylaw St',
        'Maori Hill, Stonelaw Tce',
        'Maori Hill, Tolcarne Ave',
        'Maori Hill, Wales St',
        'Maori Hill, Walsh Lane',
        'Marama Hall(Music)',
        'Marples Building(Otago)',
        'Maryhill, Acacia Ave',
        'Maryhill, Appold St',
        'Maryhill, Benhar St',
        'Maryhill, Bridger St',
        'Maryhill, Crewe St',
        'Maryhill, Glenpark Ave',
        'Maryhill, Kirriemuir St',
        'Maryhill, Lesney St',
        'Maryhill, Maryhill Tc',
        'Maryhill, Mitchell Ave',
        'Maryhill, Oakwood Ave',
        'Maryhill, Picardy St',
        'Maryhill, Scoular St',
        'Maryhill, Vickery PI',
        'Medical School',
        'Microbiology Building(Otago)',
        'Mornington, Aitken PI',
        'Mornington, Argyle St',
        'Mornington, Avoca St',
        'Mornington, Bowler Ave',
        'Mornington, Brunel St',
        'Mornington, Byron St',
        'Mornington, Carson St',
        'Mornington, Cochrane St',
        'Mornington, Cook St',
        'Mornington, Cooper St',
        'Mornington, Crosby St',
        'Mornington, Cross St',
        'Mornington, Dalry St',
        'Mornington, Durham St',
        'Mornington, Eglinton Rd',
        'Mornington, Galloway St',
        'Mornington, Glen Rd',
        'Mornington, Haig St',
        'Mornington, Havelock St',
        'Mornington, Hawthorn Ave',
        'Mornington, Henderson St',
        'Mornington, Iona St',
        'Mornington, Kevin St',
        'Mornington, Laurie St',
        'Mornington, Lawrence St',
        'Mornington, Longwood Ave',
        'Mornington, MacNee St',
        'Mornington, Mailer St',
        'Mornington, McCrea St',
        'Mornington, McGeorge Ave',
        'Mornington, Meadow St',
        'Mornington, Mosgiel St',
        'Mornington, Neidpath Rd',
        'Mornington, Osborne Tce',
        'Mornington, Parkhill Ave',
        'Mornington, Peel St',
        'Mornington, Porteous St',
        'Mornington, Rutland St',
        'Mornington, Springhill Rd',
        'Mornington, Ventnor St',
        'Mornington, Whitby St',
        'Movement Development Clinic',
        'Music Building',
        'Musselburgh, Alton Ave',
        'Musselburgh, Belmont Lane',
        'Musselburgh, Cavell St',
        'Musselburgh, Cranley St',
        'Musselburgh, Lochend St',
        'Musselburgh, Marama St',
        'Musselburgh, Marlow St',
        'Musselburgh, Moana Cres',
        'Musselburgh, Musselburgh Rise',
        'Musselburgh, Portobello Rd',
        'Musselburgh, Ravelston St',
        'Musselburgh, Ravelston St',
        'Musselburgh, Rawhiti St',
        'Musselburgh, Rewa St',
        'Musselburgh, Rochester Tce',
        'Musselburgh, Shore St',
        'Musselburgh, Sunshine Lane',
        'Musselburgh, Wardlaw St',
        'Normanby, Antrim St',
        'Normanby, Bonnington St',
        'Normanby, Dryden St',
        'Normanby, Echovale Ave',
        'Normanby, Hillingdon St',
        'Normanby, Morton St',
        'Normanby, Potters Rd',
        'Normanby, Ribbonwood CI',
        'Normanby, Rolla St',
        'Normanby, Tannadice St',
        'Normanby, Trafalgar St',
        'Normanby, Uxbridge St',
        'North Dunedin, Agnew St',
        'North Dunedin, Albany St',
        'North Dunedin, Brook St',
        'North Dunedin, Butts Rd',
        'North Dunedin, Clarendon St',
        'North Dunedin, Clyde St',
        'North Dunedin, Cosy Dell Rd',
        'North Dunedin, Drummond St',
        'North Dunedin, Duke St',
        'North Dunedin, Dundas St',
        'North Dunedin, Ellis St',
        'North Dunedin, Emily Siedeberg PI',
        'North Dunedin, Ethel Benjamin PI',
        'North Dunedin, Ethel McMillan PI',
        'North Dunedin, Forth St',
        'North Dunedin, Frederick St',
        'North Dunedin, Gore PI',
        'North Dunedin, Gowland St',
        'North Dunedin, Harbour Tce',
        'North Dunedin, Howe St',
        'North Dunedin, Hyde St',
        'North Dunedin, Inverleith St',
        'North Dunedin, Kyber Pass',
        'North Dunedin, Kyle St',
        'North Dunedin, Lachlan Ave',
        'North Dunedin, Leithbank',
        'North Dunedin, Logan Park Dr',
        'North Dunedin, LoveLock Ave',
        'North Dunedin, Mackenzie St',
        'North Dunedin, Malcolm St',
        'North Dunedin, Moat St',
        'North Dunedin, Montgomery Ave',
        'North Dunedin, Park St',
        'North Dunedin, Pitt St',
        'North Dunedin, Queen St',
        'North Dunedin, Quentin Ave',
        'North Dunedin, Regent Rd',
        'North Dunedin, Riego St',
        'North Dunedin, St Abbs PI',
        'North Dunedin, St David St',
        'North Dunedin, Titan St',
        'North Dunedin, Trent Ave',
        'North Dunedin, Union PI',
        'North Dunedin, Union St',
        'North Dunedin, Walsh St',
        'North Dunedin, Warrender St',
        'North Dunedin, Willowbank',
        'North East Valley, Afton Tce',
        'North East Valley, Ainslee PI',
        'North East Valley, Allen St',
        'North East Valley, Arden St',
        'North East Valley, Arnold St',
        'North East Valley, Baldwin St',
        'North East Valley, Bank St',
        'North East Valley, Barclay St',
        'North East Valley, Beechworth St',
        'North East Valley, Birchfield Ave',
        'North East Valley, Blacks Rd',
        'North East Valley, Bouverie St',
        'North East Valley, Buccleugh St',
        'North East Valley, Buchanan St',
        'North East Valley, Calder Ave',
        'North East Valley, Cardigan St',
        'North East Valley, Carlton St',
        'North East Valley, Carlyle St',
        'North East Valley, Carr St',
        'North East Valley, Chamber St',
        'North East Valley, Chester St',
        'North East Valley, Coburn Ave',
        'North East Valley, Cornhill St',
        'North East Valley, Craigleith St',
        'North East Valley, Crown St',
        'North East Valley, Croydon St',
        'North East Valley, Dalkeith St',
        'North East Valley, Dalmeny St',
        'North East Valley, Dolphin St',
        'North East Valley, Duddingstone Stps',
        'North East Valley, Felix St',
        'North East Valley, Frame St',
        'North East Valley, Gillespie',
        'North East Valley, Glencairn',
        'North East Valley, Glendining Ave',
        'North East Valley, Grey St',
        'North East Valley, Harold St',
        'North East Valley, Islington St',
        'North East Valley, James St',
        'North East Valley, Jura St',
        'North East Valley, Kelvin Rd',
        'North East Valley, Knox S',
        'North East Valley, Langham Tce',
        'North East Valley, Lazar St',
        'North East Valley, Leicester St',
        'North East Valley, Lennox St',
        'North East Valley, Logie St',
        'North East Valley, Longworth St',
        'North East Valley, Lucan St',
        'North East Valley, Maybank St',
        'North East Valley, Mechanic St',
        'North East Valley, Montague St',
        'North East Valley, Montrose St',
        'North East Valley, North Rd',
        'North East Valley, Northumberland St',
        'North East Valley, Opoho Rd',
        'North East Valley, Paisley Ave',
        'North East Valley, Paris St',
        'North East Valley, Pentland St',
        'North East Valley, Pleasant PI',
        'North East Valley, Primrose Bank',
        'North East Valley, Queensberry St',
        'North East Valley, Radnor St',
        'North East Valley, Rhodes Tce',
        'North East Valley, Rodney St',
        'North East Valley, Royston St',
        'North East Valley, Scone Ave',
        'North East Valley, Selwyn St',
        'North East Valley, Taine St',
        'North East Valley, Watts Rd',
        'OUSA House(Otago)',
        'Ocean Grove, Domain Ave',
        'Ocean Grove, Lombardy St',
        'Ocean Grove, Luck St',
        'Ocean Grove, Oregon St',
        'Ocean Grove, Tomahawk Rd',
        'Ocean View, Bennett Rd',
        'Ocean View, Brighton Rd',
        'Ocean View, Creamery Rd',
        'Ocean View, Edna St',
        'Ocean View, Hare Rd',
        'Ocean View, John St',
        'Ocean View, Kayforce Rd',
        'Ocean View, McColl Rd',
        'Ocean View, Rockview Rd',
        'Opoho, Balmoral St',
        'Opoho, Colin St',
        'Opoho, Comely Bank',
        'Opoho, Evans St',
        'Opoho, Farquharson St',
        'Opoho, Grandview Cres',
        'Opoho, Hatfield St',
        'Opoho, Mowat St',
        'Opoho, Northfield Ave',
        'Opoho, Roxburgh St',
        'Opoho, Signal Hill Rd',
        'Opoho, Sylvan St',
        'Opoho, Torridon St',
        'Opoho, Warden St',
        'Opoho, Windsor St',
        'Physiotherapy Building',
        'Pine Hill, Abbeyhill Rd',
        'Pine Hill, Beaufort St',
        'Pine Hill, Campbells Rd',
        'Pine Hill, Cowan Rd',
        'Pine Hill, Dalrymple St',
        'Pine Hill, Maxwellton St',
        'Pine Hill, Meldrum St',
        'Pine Hill, Pinedale PI',
        'Pine Hill, Watkin St',
        'Portobello, Allans Beach Rd',
        'Portobello, Arnott St',
        'Portobello, Beaconsfield Rd',
        'Portobello, Blackwell St',
        'Portobello, Densem St',
        'Portobello, Geary St',
        'Portobello, Hanson St',
        'Portobello, Harington Point Rd',
        'Portobello, Hatchery Rd',
        'Portobello, Hereweka St',
        'Portobello, Highcliff Rd',
        'Portobello, Landreth St',
        'Portobello, McAuley Rd',
        'Portobello, Melrose St',
        'Portobello, Moss St',
        'Portobello, Nicholas St',
        'Portobello, Ridley Rd',
        'Portobello, Ryan St',
        'Portobello, Seaton Rd',
        'Portobello, Sherwood St',
        'Portobello, Tily st',
        'Portobello, Treetop Dr',
        'Ravensbourne, Adderley Tce',
        'Ravensbourne, Ascog Rd',
        'Ravensbourne, Athol PI',
        'Ravensbourne, Ellesmere St',
        'Ravensbourne, Hawea St',
        'Ravensbourne, Hinau St',
        'Ravensbourne, Junction Rd',
        'Ravensbourne, Kauri St',
        'Ravensbourne, Kowhai St',
        'Ravensbourne, Manuka St',
        'Ravensbourne, Mark St',
        'Ravensbourne, Matai St',
        'Ravensbourne, Monowai Rd',
        'Ravensbourne, Ocean View Rd',
        'Ravensbourne, Ohau St',
        'Ravensbourne, Rata St',
        'Ravensbourne, Ravensbourne Rd',
        'Ravensbourne, Rimu St',
        'Ravensbourne, Seddon St',
        'Ravensbourne, Short St',
        'Ravensbourne, Taupo Lane',
        'Ravensbourne, Tekapo St',
        'Ravensbourne, Totara St',
        'Ravensbourne, Waireka St',
        'Ravensbourne, Wakatipu St',
        'Ravensbourne, Wanaka St',
        'Richardson Building(Otago)',
        'Robertson Library(Otago)',
        'Roslyn, Avon St',
        'Roslyn, Bruce St',
        'Roslyn, Charlotte St',
        'Roslyn, City Rd',
        'Roslyn, Duchess Ave',
        'Roslyn, Erin St',
        'Roslyn, Garfield Ave',
        'Roslyn, Hereford St',
        'Roslyn, Highgate',
        'Roslyn, Kilgour St',
        'Roslyn, Lawson St',
        'Roslyn, Leven St',
        'Roslyn, Littlebourne Rd',
        'Roslyn, Melrose St',
        'Roslyn, Merlin St',
        'Roslyn, Pacific St',
        'Roslyn, Ross St',
        'Roslyn, Scarba St',
        'Roslyn, Selkirk St',
        'Roslyn, Sheen St',
        'Roslyn, Sligo Tce',
        'Roslyn, Strathmore Cres',
        'Roslyn, Stuart St',
        'Roslyn, Tweed St',
        'Roslyn, Tyne St',
        'Roslyn, Wallace St',
        'Saint Clair, Aberdeen Rd',
        'Saint Clair, Achilles Ave',
        'Saint Clair, Albert St',
        'Saint Clair, Allandale Rd',
        'Saint Clair, Beach St',
        'Saint Clair, Bedford St',
        'Saint Clair, Clayton St',
        'Saint Clair, Cliffs Rd',
        'Saint Clair, Coney Hill Rd',
        'Saint Clair, Coughtrey St',
        'Saint Clair, Earls Rd',
        'Saint Clair, Erskine PI',
        'Saint Clair, Esplanade',
        'Saint Clair, Fenton Cres',
        'Saint Clair, Forbury Rd',
        'Saint Clair, Highgrove',
        'Saint Clair, Hobson St',
        'Saint Clair, Ings Ave',
        'Saint Clair, Isadore Rd',
        'Saint Clair, Kennedy St',
        'Saint Clair, Lock St',
        'Saint Clair, Massey Ave',
        'Saint Clair, Mavis St',
        'Saint Clair, Moana Rua Rd',
        'Saint Clair, Motu St',
        'Saint Clair, Nile St',
        'Saint Clair, Norfolk St',
        'Saint Clair, Pretoria Ave',
        'Saint Clair, Ravenswood Rd',
        'Saint Clair, Second Beach Rd',
        'Saint Clair, Sutcliffe St',
        'Saint Clair, Valpy St',
        'Saint Clair, West Ave',
        'Saint Clair, Wilson Ave',
        'Saint Clair, Wycolla Ave',
        'Saint Kilda, Ajax St',
        'Saint Kilda, Alma St',
        'Saint Kilda, Annex St',
        'Saint Kilda, Ascot St',
        'Saint Kilda, Auld St',
        'Saint Kilda, Begg St',
        'Saint Kilda, Bellona St',
        'Saint Kilda, Bird St',
        'Saint Kilda, Calder St',
        'Saint Kilda, Churchill St',
        'Saint Kilda, Corunna St',
        'Saint Kilda, Council St',
        'Saint Kilda, Cranley St',
        'Saint Kilda, Crete St',
        'Saint Kilda, Culling St',
        'Saint Kilda, Dalgety St',
        'Saint Kilda, De Carle St',
        'Saint Kilda, Douglas S',
        'Saint Kilda, East Ave',
        'Saint Kilda, Eskvale St',
        'Saint Kilda, Freyberg St',
        'Saint Kilda, Gourley St',
        'Saint Kilda, Grove St',
        'Saint Kilda, Hargest Cres',
        'Saint Kilda, Jackson St',
        'Saint Kilda, Kings Ave',
        'Saint Kilda, Larkworthy St',
        'Saint Kilda, Market St',
        'Saint Kilda, Marlow St',
        'Saint Kilda, Mills St',
        'Saint Kilda, Montreal St',
        'Saint Kilda, Moreau St',
        'Saint Kilda, New St',
        'Saint Kilda, Normanby St',
        'Saint Kilda, Onslow St',
        'Saint Kilda, Plunket St',
        'Saint Kilda, Prince Albert Rd',
        'Saint Kilda, Queens Dr',
        'Saint Kilda, Ravelston St',
        'Saint Kilda, Richardson St',
        'Saint Kilda, Rona St',
        'Saint Kilda, Royal St',
        'Saint Kilda, Rugby St',
        'Saint Kilda, Scott St',
        'Saint Kilda, Tedder St',
        'Saint Kilda, Trafalgar St',
        'Saint Kilda, Victoria Rd',
        'Saint Kilda, Waterloo St',
        'Saint Kilda, Young St',
        'Saint Leonards, Burkes Dr',
        'Saint Leonards, Eagle St',
        'Saint Leonards, Finch St',
        'Saint Leonards, Gannet Lane',
        'Saint Leonards, Harrier Rd',
        'Saint Leonards, Hawk Lane',
        'Saint Leonards, Huia St',
        'Saint Leonards, Kaka Rd',
        'Saint Leonards, Kea St',
        'Saint Leonards, Kiwi St',
        'Saint Leonards, Korimako St',
        'Saint Leonards, Moa St',
        'Saint Leonards, Pukeko St',
        'Saint Leonards, Robin Lane',
        'Saint Leonards, Ruru Ave',
        'Saint Leonards, St Leonards Dr',
        'Saint Leonards, Takahe Tce',
        'Saint Leonards, Tui St',
        'Saint Leonards, Weka St',
        'Saint Leonards, Wren Lane',
        'Sayers Building(Otago)',
        'Science library(Otago)',
        'Scott Building(Otago)',
        'Scott/Shand House',
        'Shiel Hill, Albion St',
        'Shiel Hill, Bone St',
        'Shiel Hill, Calvert PI',
        'Shiel Hill, Elliffe PI',
        'Shiel Hill, Gowan CI',
        'Shiel Hill, Highcliff Rd',
        'Shiel Hill, Mckerrow St',
        'Shiel Hill, Moodie St',
        'Shiel Hill, Murano St',
        'Shiel Hill, Portland PI',
        'South Dunedin, Andersons Bay',
        'South Dunedin, Arney St',
        'South Dunedin, Atkinson St',
        'South Dunedin, Bathgate St',
        'South Dunedin, Bay View Rd',
        'South Dunedin, Bradshaw St',
        'South Dunedin, Braemar St',
        'South Dunedin, Brandon St',
        'South Dunedin, Broughton St',
        'South Dunedin, Burns St',
        'South Dunedin, Cameron St',
        'South Dunedin, Carey Ave',
        'South Dunedin, Cashel St',
        'South Dunedin, Colston St',
        'South Dunedin, Cutten St',
        'South Dunedin, Dick St',
        'South Dunedin, Fawcett St',
        'South Dunedin, Fingall St',
        'South Dunedin, Fox St',
        'South Dunedin, Glasgow St',
        'South Dunedin, Hall St',
        'South Dunedin, Hillside Rd',
        'South Dunedin, Kensington Ave',
        'South Dunedin, King Edward St',
        'South Dunedin, Kirkcaldy St',
        'South Dunedin, Largo Ave',
        'South Dunedin, Lorne St',
        'South Dunedin, MacAndrew Rd',
        'South Dunedin, McBride St',
        'South Dunedin, Melbourne St',
        'South Dunedin, Midland St',
        'South Dunedin, Millington St',
        'South Dunedin, Neville St',
        'South Dunedin, Orari St',
        'South Dunedin, Osmond St',
        'South Dunedin, Otaki St',
        'South Dunedin, Oxford St',
        'South Dunedin, Portsmouth Dr',
        'South Dunedin, Prendergast St',
        'South Dunedin, Rankeilor St',
        'South Dunedin, Reid Rd',
        'South Dunedin, Rowland Ave',
        'South Dunedin, Samuel St',
        'South Dunedin, Strathallan St',
        'South Dunedin, Sullivan Ave',
        'South Dunedin, Teviot St',
        'South Dunedin, Thomas St',
        'South Dunedin, Timaru St',
        'South Dunedin, Turakina Rd',
        'South Dunedin, Waverley St',
        'South Dunedin, Wesley St',
        'South Dunedin, Wynyard St',
        'St David II (Otago)',
        'St Davids Lecture Theatre(Otago)',
        'Tainui, Angle Ave',
        'Tainui, Aotea St',
        'Tainui, Arawa St',
        'Tainui, Botha St',
        'Tainui, Chisholm PI',
        'Tainui, Crest St',
        'Tainui, Dundonald St',
        'Tainui, Gresham St',
        'Tainui, Kamura St',
        'Tainui, Magdala St',
        'Tainui, Norman St',
        'Tainui, Spottiswoode St',
        'Tainui, Tahuna Rd',
        'Tainui, Tainui Rd',
        'Tainui, Te Ra Tce',
        'Te Tumu',
        'The Glen, Eglinton Rd',
        'The Glen, Elbe St',
        'The Glen, Haywood St',
        'The Glen, Patrick St',
        'The Glen, Reynolds St',
        'The Glen, Walter St',
        'Union Court(Otago)',
        'University Book shop(Otago)',
        'University Plaza Building(Otago)',
        'Vauxhall, Arthurs WIk',
        'Vauxhall, Braeburn St',
        'Vauxhall, Challis St',
        'Vauxhall, Cornwall St',
        'Vauxhall, Danube St',
        'Vauxhall, Glendevon PI',
        'Vauxhall, Glengyle St',
        'Vauxhall, Portobello Rd',
        'Vauxhall, Shandon Rd',
        'Vauxhall, Torr St',
        'Wakari, Balmacewen Rd',
        'Wakari, Berwick St',
        'Wakari, Blantyre Rd',
        'Wakari, Broomlea St',
        'Wakari, Burt St',
        'Wakari, Chapman St',
        'Wakari, Cohen PI',
        'Wakari, Craaighall Cres',
        'Wakari, Crichton St',
        'Wakari, Cromwell St',
        'Wakari, Edgar St',
        'Wakari, Ethel St',
        'Wakari, Ferntree Dr',
        'Wakari, Forresbank Ave',
        'Wakari, Gilmore St',
        'Wakari, Greenhill Ave',
        'Wakari, Hastings St',
        'Wakari, Holyrood Ave',
        'Wakari, Hood St',
        'Wakari, Lynn St',
        'Wakari, Mayfield Ave',
        'Wakari, Mount St',
        'Wakari, Oliver St',
        'Wakari, Pennant St',
        'Wakari, Prospect Bank',
        'Wakari, Rosebank Ave',
        'Wakari, Shetland St',
        'Wakari, Strathearn Ave',
        'Waldronville, Canberra PI',
        'Waldronville, Craddock PI',
        'Waldronville, Dakota PI',
        'Waldronville, Delta Dr',
        'Waldronville, Friendship Dr',
        'Waldronville, Kilmarnock CI',
        'Waldronville, Valiant Rd',
        'Waldronville, Vampire Rd',
        'Waldronville, Viscount Rd',
        'Waldronville, Vulcan Rd',
        'Waldronville, Wavy Knowes Dr',
        'Walsh Building - School of Dentistry',
        'Waverley, Archibald St',
        'Waverley, Aytoun St',
        'Waverley, Ballantyne St',
        'Waverley, Beatty St',
        'Waverley, Belford St',
        'Waverley, Beverley PI',
        'Waverley, Botting PI',
        'Waverley, Brugh PI',
        'Waverley, Cawdor PI',
        'Waverley, Connell St',
        'Waverley, Coolock Cres',
        'Waverley, Dinmont St',
        'Waverley, Doon St',
        'Waverley, Dunrobin St',
        'Waverley, Eastbank St',
        'Waverley, Gala St',
        'Waverley, Harbour Hts',
        'Waverley, Kenilworth St',
        'Waverley, Kipling St',
        'Waverley, Larnach Rd',
        'Waverley, Mannering St',
        'Waverley, Marne St',
        'Waverley, Mathieson St',
        'Waverley, Scobie St',
        'Waverley, Scott St',
        'Waverley, Tower Ave',
        'Wellcome Building(Otago)',
        'Woodhaugh, Harden st',
        'Woodhaugh, Malvern St',
        'Woodhaugh, Patmos Ave',
        'Woodhaugh, Woodhaugh St',
        'Zoology Annexe(Otago)'
      ],
      // end
      noteRules: [
        v => !!v || 'Note is required',
        v => (v && v.length <= 100) || 'Note must be less than 100 characters'
      ],
      image: null,
      dialog: false,
      notifications: false,
      imageBanner: require('@/assets/img/home-ban.png'),
      // set input rules
      rules: {
        required: value => !!value || 'Required.'
      },
      // set regions input selection
      search: null
    }
  },
  computed: {
    formIsValid () {
      return this.category !== '' && this.foundAt !== '' && this.note !== '' && this.imageUrl !== ''
    }
  },
  mounted () {
    console.log(firebase.auth().currentUser)
  },
  methods: {
    // create a document in cloud firestore
    onCreateWarehouseItem () {
      db.collection('warehouses').add({
        category: this.category,
        imageUrl: this.imageUrl,
        foundAt: this.foundAt,
        note: this.note,
        UploadDate: new Date().toISOString()
      })
        .then(docRef => this.$router.push('/lostFoundsWarehouses'))
        // eslint-disable-next-line handle-callback-err
        .catch(error => this.$swal({
          title: 'Invalid Image Size!',
          text: 'Image size has to be less than 1MB!',
          confirmButtonColor: '#4FC3F7',
          iconColor: '#FFB300',
          imageUrl: require('@/assets/img/warning.png')
        }))
    },
    onPickFile () {
      this.$refs.fileInput.click()
    },
    onFilePicked (event) {
      const files = event.target.files
      let filename = files[0].name
      if (filename.lastIndexOf('.') <= 0) {
        return alert('Please pick a valid image format!')
      }
      // use fileReade read files that users typed
      const fileReader = new FileReader()
      fileReader.addEventListener('load', () => {
        this.imageUrl = fileReader.result
      })
      fileReader.readAsDataURL(files[0])
      this.image = files[0]
    }

  }
}
</script>

<style lang="stylus" scoped>@import '../stylus/main.styl'
.tooltip-text
  font-family Montserrat
.form-text-heading
  color #424242
.home-btn
  margin-top 11rem
  .btn-grad
    font-family Montserrat
    width:40%
    word-spacing 0.25rem
  //.btn-grad:hover
  +for_breakpoint(desktop)
    .btn-grad
      width:50%
  +for_breakpoint(tablet)
    .btn-grad
      width 65%
  +for_breakpoint(mobile)
    .btn-grad
      width 86%
  +for_breakpoint(tinymobile)
    .btn-grad
      width 100%
  .upload-text
    font-family "Helvetica Neue"
  .form-text-font
    font-family "Adobe Caslon Pro"

</style>
